### ISSUE TITLE
Errors When Adding Package

### ISSUE THREAD

**Issue by strangeattractor72** [gher-ulg/DIVAnd_HFRadar.jl#1]
Hello,

I have been trying to use this package and keep getting the same errors when running Pkg.add("DIVAnd_HFRadar"). I'm wondering if anyone has seen this before.

    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
   Installed Adapt ─────────────── v3.4.0
   Installed Scratch ───────────── v1.1.1
   Installed URIs ──────────────── v1.4.0
   Installed TranscodingStreams ── v0.9.6
   Installed LoggingExtras ─────── v0.4.9
   Installed SimpleBufferStream ── v1.1.0
   Installed Mustache ──────────── v1.0.14
   Installed StaticArrays ──────── v1.5.2
   Installed NCDatasets ────────── v0.11.9
   Installed NetCDF_jll ────────── v400.702.402+0
   Installed MbedTLS ───────────── v1.1.1
   Installed HDF5_jll ──────────── v1.12.2+1
   Installed LogExpFunctions ───── v0.3.17
   Installed Glob ──────────────── v1.3.0
   Installed ChainRulesCore ────── v1.15.3
   Installed HTTP ──────────────── v1.2.0
   Installed CodecZlib ─────────── v0.7.0
   Installed ChangesOfVariables ── v0.1.4
   Installed DIVAnd_HFRadar ────── v0.1.0
   Installed DocStringExtensions ─ v0.9.1
   Installed Pluto ─────────────── v0.19.11
  Downloaded artifact: NetCDF
  Downloaded artifact: HDF5
    Updating `~/.julia/environments/v1.7/Project.toml`
  [7f46824f] + DIVAnd_HFRadar v0.1.0
  [85f8d34a] ↓ NCDatasets v0.12.5 ⇒ v0.11.9
  [c3e4b0f8] ↑ Pluto v0.19.9 ⇒ v0.19.11
    Updating `~/.julia/environments/v1.7/Manifest.toml`
  [79e6a3ab] ↑ Adapt v3.3.3 ⇒ v3.4.0
  [d360d2e6] ↑ ChainRulesCore v1.15.1 ⇒ v1.15.3
  [9e997f8a] ↑ ChangesOfVariables v0.1.3 ⇒ v0.1.4
  [944b1d66] + CodecZlib v0.7.0
  [7f46824f] + DIVAnd_HFRadar v0.1.0
  [ffbed154] ↑ DocStringExtensions v0.8.6 ⇒ v0.9.1
  [c27321d9] + Glob v1.3.0
  [cd3eb016] ↑ HTTP v0.9.17 ⇒ v1.2.0
  [2ab3a3ac] ↑ LogExpFunctions v0.3.15 ⇒ v0.3.17
  [e6f89c97] + LoggingExtras v0.4.9
  [739be429] ↑ MbedTLS v1.1.0 ⇒ v1.1.1
  [ffc61752] ↑ Mustache v1.0.13 ⇒ v1.0.14
  [85f8d34a] ↓ NCDatasets v0.12.5 ⇒ v0.11.9
  [c3e4b0f8] ↑ Pluto v0.19.9 ⇒ v0.19.11
  [6c6a2e73] ↑ Scratch v1.1.0 ⇒ v1.1.1
  [777ac1f9] + SimpleBufferStream v1.1.0
  [90137ffa] ↑ StaticArrays v1.5.0 ⇒ v1.5.2
  [3bb67fe8] + TranscodingStreams v0.9.6
  [5c2747f8] ↑ URIs v1.3.0 ⇒ v1.4.0
  [0234f1f7] ↑ HDF5_jll v1.12.0+1 ⇒ v1.12.2+1
  [7243133f] ↑ NetCDF_jll v400.702.400+0 ⇒ v400.702.402+0
Precompiling project...
  ✗ NCDatasets
  ✗ DIVAnd
  ✗ DIVAnd_HFRadar
  24 dependencies successfully precompiled in 20 seconds (54 already precompiled)
  3 dependencies errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the packages

This leads to the following issue when trying to use the package:

ERROR: LoadError: InitError: could not load library "/home/charlesunderhill/.julia/artifacts/a990d3d23ca4ca4c1fcd1e42fc198f1272f7c49b/lib/libnetcdf.so"
libmbedtls.so.13: cannot open shared object file: No such file or directory
Stacktrace:
 [1] macro expansion
   @ ~/.julia/packages/JLLWrappers/QpMQW/src/products/library_generators.jl:54 [inlined]
 [2] __init__()
   @ NetCDF_jll ~/.julia/packages/NetCDF_jll/2PbeF/src/wrappers/x86_64-linux-gnu.jl:14
 [3] top-level scope (repeats 2 times)
   @ none:1
during initialization of module NetCDF_jll
in expression starting at /home/charlesunderhill/.julia/packages/NCDatasets/c8XyT/src/NCDatasets.jl:1
ERROR: LoadError: Failed to precompile NCDatasets [85f8d34a-cbdd-5861-8df4-14fed0d494ab] to /home/charlesunderhill/.julia/compiled/v1.7/NCDatasets/jl_CfHpOL.
Stacktrace:
 [1] top-level scope (repeats 2 times)
   @ none:1
in expression starting at /home/charlesunderhill/.julia/packages/DIVAnd/Mbj6v/src/DIVAnd.jl:1
ERROR: LoadError: Failed to precompile DIVAnd [efc8151c-67de-5a8f-9a35-d8f54746ae9d] to /home/charlesunderhill/.julia/compiled/v1.7/DIVAnd/jl_u44IXt.
Stacktrace:
 [1] top-level scope (repeats 2 times)
   @ none:1
in expression starting at /home/charlesunderhill/.julia/packages/DIVAnd_HFRadar/bVLSN/src/DIVAnd_HFRadar.jl:3
ERROR: LoadError: Failed to precompile DIVAnd_HFRadar [7f46824f-871f-4a07-b57f-28974f6a6036] to /home/charlesunderhill/.julia/compiled/v1.7/DIVAnd_HFRadar/jl_8V9VQh.
in expression starting at /home/charlesunderhill/DIVAnd_HFRadartest.jl:1

**Comment by jmbeckers** [comment]
Which Julia version are you using? Maybe related to
https://alexander-barth.github.io/NCDatasets.jl/dev/issues/#Using-non-official-julia-builds

If you use a preinstalled julia version on a Linux system, you might need to install and use the latest version from
https://julialang.org/downloads/

**Comment by strangeattractor72** [comment]
I'm using Version 1.7.3 (2022-05-06)
Fedora 36 build

**Comment by jmbeckers** [comment]
Then you need to use rather the official build from https://julialang.org/downloads/

See discussion and explanation why this happens at the end of  https://github.com/gher-ulg/DIVAnd.jl/issues/104

(in the present case forcing NetCDF_jll v400.802.103+0 seems to work but is not a generic approach).

**Comment by jmbeckers** [comment]
Closing the issue assuming using the official Julia version solved the problem.
